# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f4bc7c488408e565a89b3bc9fced7071f83cae900c25411d8eb0bc09d2aad56ad1e51a5738c382a9d02871a2841216f5b8bead6838d2a576b4aee07f467764a0

test:
  secret_key_base: 265c6b291f6f3056b0bf73362bc98e43c887379f5cc2612c772ffecf7b2a53fb9ef490a803a9c39a52af96bd885efb5f66e5e70eb4906a2b01b25c505c730084

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
